services:

  postgres_data:
    image: postgres:14
    container_name: tm_postgres_data
    environment:
      POSTGRES_USER: ${POSTGRES_DATA_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DATA_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATA_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_DATA_USER}"]
      interval: 10s
      timeout: 5s
      retries: 10

  postgres_mlflow:
    image: postgres:14
    container_name: tm_postgres_mlflow
    environment:
      POSTGRES_USER: ${POSTGRES_MLFLOW_USER}
      POSTGRES_PASSWORD: ${POSTGRES_MLFLOW_PASSWORD}
      POSTGRES_DB: ${POSTGRES_MLFLOW_DB}
    volumes:
      - postgres_mlflow:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_MLFLOW_USER}"]
      interval: 10s
      timeout: 5s
      retries: 10

  minio:
    image: bitnamilegacy/minio:latest
    container_name: tm_minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_DEFAULT_BUCKETS: ${MINIO_BUCKET}
      MINIO_BROWSER: "on"
      MINIO_CONSOLE_PORT_NUMBER: "9001"
    ports:
      - "8003:9000"
      - "8002:9001"
    volumes:
      - minio_data:/bitnami/minio/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 10

  mlflow:
    build: ./mlflow
    container_name: tm_mlflow
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri postgresql+psycopg2://${POSTGRES_MLFLOW_USER}:${POSTGRES_MLFLOW_PASSWORD}@postgres_mlflow:5432/${POSTGRES_MLFLOW_DB}
      --default-artifact-root s3://${MINIO_BUCKET}/
      --serve-artifacts
    environment:
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
    ports:
      - "8001:5000"
    depends_on:
      postgres_mlflow:
        condition: service_healthy
      minio:
        condition: service_healthy
    restart: always

volumes:
  postgres_data:
  postgres_mlflow:
  minio_data:
